# Generated by Django 5.1.2 on 2024-10-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_requests", "0004_alter_gamerequest_game_alter_gamerequest_mate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerequest",
            name="review_status",
            field=models.BooleanField(default=False),
        ),
    ]
