# version: '3.8'

services:
  django_gunicorn:
    container_name: django_gunicorn
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DB_HOST=${RDS_HOSTNAME}
      - DB_NAME=${RDS_DB_NAME}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
      - SKIP_MIGRATIONS=True
    env_file:
      - .env
    networks:
      - app_network

  daphne:
    container_name: django_daphne
    build: .
    entrypoint: /app/entrypoint.sh
    expose:
      - "8001"
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DB_HOST=${RDS_HOSTNAME}
      - DB_NAME=${RDS_DB_NAME}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - ./resources/cert/fullchain.pem:/etc/letsencrypt/live/resdineconsulting.com/fullchain.pem
      - ./resources/cert/privkey.pem:/etc/letsencrypt/live/resdineconsulting.com/privkey.pem

    networks:
      - app_network

  redis:
    image: redis:7.0
    container_name: main-project-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  static_volume:
  media_volume:


