# version: '3.8'

services:
  gunicorn:
    container_name: vita_gunicorn
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DB_HOST=${RDS_HOSTNAME}
      - DB_NAME=${RDS_DB_NAME}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
      - SKIP_MIGRATIONS=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    command: /bin/bash -c "source ~/.bashrc && cd /app/src && poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - app_network

  daphne:
    container_name: vita_daphne
    build: .
    entrypoint: /app/entrypoint.sh
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - daphne_socket:/app/daphne_socket # UNIX 소켓을 위한 볼륨 추가
    environment:
      - DB_HOST=${RDS_HOSTNAME}
      - DB_NAME=${RDS_DB_NAME}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    command: /bin/bash -c "source ~/.bashrc && cd /app/src && poetry run daphne -u /app/daphne_socket/daphne.sock config.asgi:application"
    networks:
      - app_network
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - daphne_socket:/app/daphne_socket
    networks:
      - app_network
    depends_on:
      - daphne
      - gunicorn

  redis:
    image: redis:7.0
    container_name: vita-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  static_volume:
  media_volume:
  daphne_socket:


