# Generated by Django 5.1.2 on 2024-10-25 13:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="order_name",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="requested_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
