# Generated by Django 5.1.2 on 2024-10-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_requests", "0004_alter_gamerequest_game_alter_gamerequest_mate_and_more"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="game_request",
            field=models.ForeignKey(
                db_column="game_request_id", on_delete=django.db.models.deletion.CASCADE, to="game_requests.gamerequest", unique=True
            ),
        ),
    ]
