# Generated by Django 5.1.2 on 2024-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_rename_text_message_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="chatroomuser",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
    ]
