# Generated by Django 5.1.2 on 2024-11-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_remove_message_updated_at_chatroomuser_unread_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="latest_message",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="latest_in_room", to="chats.message"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="latest_message_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
